# Project Information
site_name: ASPEN
site_author: CCBR
site_description: >-
  **A**tac **S**eq **P**ip**E**li**N**e

# Repository
repo_name: CCBR/ASPEN
repo_url: https://github.com/CCBR/ASPEN
edit_uri: https://github.com/CCBR/ASPEN/edit/main/docs/

# Copyright
copyright: Copyright &copy; 2023 CCBR

# Configuration
theme:
  name: readthedocs
  locale: en
  custom_dir: docs/overrides
  #
# Plugins
plugins:
  - search
  - git-revision-date
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - icon: fontawesome/solid/users
      link: http://bioinformatics.cancer.gov
    - icon: fontawesome/brands/github
      link: https://github.com/CCBR
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/orgs/nciccbr/repositories
  # version:
  #   provider: mike

extra_css:
  - css/custom.css
extra_javascript:
  - js/custom.js

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Background: index.md
  - Introduction to ATAC-seq: introduction.md
  - Overview of ASPEN: overview.md
  - Running ASPEN: deployment.md
  - ASPEN Output: outputs.md
  - Limitations of ASPEN: limitations.md
  - Communications: communications.md
  - Change Log: changelog.md
  - Contributing to ASPEN: contributing.md
